Models/CreateSeller.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;


namespace Project_Web.Models
{
    public class CreateSeller
    {
        [MinLength(8, ErrorMessage = "Tên ít nhất 8 kí tự")]
        [RegularExpression(@"^(([A-za-z0-9]+[\s]{1}[A-za-z0-9]+)|([A-Za-z0-9]+))$", ErrorMessage = "Tên của bạn phải chứa chữ cái viết thường hoặc hoa, VD: Huutuong")]
        public string Username { get; set; }
        [MinLength(8, ErrorMessage = "Mật khẩu phải nhập ít nhất 8 kí tự")]
        [RegularExpression(@"^(?=.*\d)(?=.*[a-z])(?=.*[A-Z])(?=.*[a-zA-Z]).{8,}$", ErrorMessage = "Mật khẩu phải chứa chữ in hoa, số hoặc ký tự đặc biệt")]
        [Required(ErrorMessage = "Mật khẩu không được trống!")]
        public string Password { get; set; }
        [Required(ErrorMessage = "Họ tên không được trống!")]
        public string Fullname
        {
            get; set;
        }
        [Required(ErrorMessage = "Địa chỉ không được trống")]
        public string Address { get; set; }
        [Required(ErrorMessage = "Số điện thoại không được trống")]
        [RegularExpression(@"(03|07|08|09|01[2|6|8|9])+([0-9]{8})", ErrorMessage = "Hãy nhập số điện thoại hợp lệ, VD:03xxxxxxxx")]
        public string PhoneNumber { get; set; }
        [Required(ErrorMessage = "Email không được trống")]
        [RegularExpression(@"\A(?:[A-Za-z0-9!#$%&'*+/=?^_`{|}~-]+(?:\.[A-Za-z0-9!#$%&'*+/=?^_`{|}~-]+)*@(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?)\Z",
                           ErrorMessage = "Hãy nhập email hợp lệ, VD: huutuong@gmail.com")]
        public string Email { get; set; }
        public string Role { get; set; }
    }

}

Controllers/Administrator_SettingController.cs
using Project_Web.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity.Migrations;
using System.Data.Entity.Validation;
using System.Data.OleDb;
using System.Text.RegularExpressions;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.DynamicData;
using System.Web.Mvc;
using System.Web.UI;
using PagedList;
using System.Data;
using LinqToExcel;

namespace Project_Web.Controllers
{
    [AuthorizeController]
    public class Administrator_SettingController : BaseController
    {

        public Database_PorridgeSellingManagementStoreEntities _db = new Database_PorridgeSellingManagementStoreEntities();
        // GET: Administrator_Setting

        #region CreateSeller
        [HttpGet]
        public ActionResult CreateSeller()
        {
            return View();
        }
        [HttpPost]
        public ActionResult CreateSeller(CreateSeller model, FormCollection form)
        {
            User user = _db.Users.SingleOrDefault(n => n.Username == model.Username);
            User email = _db.Users.SingleOrDefault(n => n.Email == model.Email);
            var province = form["Province"];
            var district = form["District"];
            var ward = form["Ward"];
            var re_password = form["re_password"];

            //Validate
            if (user is null && email is null)
            {
                if (re_password != model.Password)
                    return Content("password");
                else
                {
                    EncryptionPW encryptionPW = new EncryptionPW(model.Password);
                    model.Password = encryptionPW.EncryptPass();
                    if (ModelState.IsValid)
                    {
                        User usertemp = new User();
                        User_Roles User_Role = new User_Roles();
                        Address_Users address_Users = new Address_Users();
                        if (province is null || district is null)
                        {
                            if (province is null)
                                return Content("province");
                            if (district is null)
                                return Content("district");
                        }
                        else
                        {
                            if (ward is null)
                                ward = "";
                            //Add user into "User" table
                            var querryUsersCount = from User in _db.Users
                                                   select User.IDUser;
                            usertemp.IDUser = "U" + querryUsersCount.Count() + "-" + String.Format("{0:ddMMyyyyHHmmss}", DateTime.Now);

                            usertemp.Username = model.Username;
                            usertemp.Password = model.Password;
                            usertemp.Fullname = model.Fullname;
                            usertemp.Address = form["Address"].ToString();
                            usertemp.PhoneNumber = model.PhoneNumber;
                            usertemp.Email = model.Email;
                            usertemp.Image = "Null";
                            usertemp.Facebook = "0";
                            _db.Users.Add(usertemp);

                            //Add role of User into "User_Role" table
                            string roletemp = model.Role;
                            if (model.Role is null)
                            {
                                return Content("role");
                            }
                            else
                            {
                                User_Role.IDUser = usertemp.IDUser;
                                var querryGetRole = (from role in _db.Roles
                                                     where role.Role1 == roletemp
                                                     select role.IDRole).SingleOrDefault();
                                User_Role.IDRole = querryGetRole.ToString();
                                _db.User_Roles.Add(User_Role);
                                _db.SaveChanges();

                                //Add address default
                                var querryaddress_UsersCount = (from au in _db.Address_Users
                                                                select au).ToList();
                                address_Users.IDAddress = "A-U" + querryaddress_UsersCount.Count() + "-" + String.Format("{0:ddMMyyyyHHmmss}", DateTime.Now);
                                address_Users.IDUser = usertemp.IDUser;
                                address_Users.Province = province;
                                address_Users.District = district;
                                address_Users.Ward = ward;
                                address_Users.IsDefault = 1;
                                address_Users.Street = form["Address"].ToString();
                                address_Users.PhoneNumber = model.PhoneNumber;
                                address_Users.Fullname = model.Fullname;
                                _db.Address_Users.Add(address_Users);
                                _db.SaveChanges();

                                return Content("true");
                            }
                        }
                    }
                    else
                    {
                        return Content("false");
                    }
                }
            }
            else
            {
                if (user != null)
                    return Content("user");
                else
                    return Content("email");
            }
            return View();
        }
        #endregion

        #region Create Store
        [HttpGet]
        public ActionResult CreateStore()
        {
            return View();
        }
        [HttpPost]
        public ActionResult CreateStore(Store model)
        {
            Store email = _db.Stores.SingleOrDefault(n => n.Email == model.Email);
            string errorMessage = null;
            if (email is null)
            {
                var querryStoresCount = from Store in _db.Stores
                                        select Store.IDStore;
                model.IDStore = "S" + querryStoresCount.Count() + "-" + String.Format("{0:ddMMyyyyHHmmss}", DateTime.Now);
                if (model.Location is null)
                {
                    return Content("nolocation");
                }
                else
                {
                    if (!ModelState.IsValidField("PhoneNumber"))
                    {
                        errorMessage = "PhoneNumber";
                        return Content(errorMessage);
                    }
                    if (ModelState.IsValid)
                    {
                        _db.Stores.Add(model);

                        //Setting Default: While creating store, creating warehouse of store
                        Warehouse warehouse = new Warehouse();
                        warehouse.IDWarehouse = "WH" + querryStoresCount.Count() + "-" + String.Format("{0:ddMMyyyyHHmmss}", DateTime.Now);
                        warehouse.WarehouseName = "Kho hàng " + model.StoreName;
                        warehouse.LocationofWarehouse = model.Location;
                        warehouse.IDStore = model.IDStore;
                        _db.Warehouses.Add(warehouse);
                        _db.SaveChanges();
                        return Content("true");
                    }
                    return Content("errormessage");
                }
            }
            else
            {
                return Content("email");
            }
        }
        #endregion

        #region Create Dish
        [HttpGet]
        public ActionResult CreateDish()
        {
            return View();
        }
        [HttpPost]
        public ActionResult CreateDish(string DishName, string Ingredient, string ImportPrice, string SalePrice, string Category, HttpPostedFileBase FileUpload)
        {

            Menu menu_temp = new Menu();
            var querryDishesCount = from Menu in _db.Menus
                                    select Menu.IDDish;
            Menu menu = _db.Menus.SingleOrDefault(n => n.DishName == DishName);
            //Validate
            if (menu == null && Category != "null" && ImportPrice != "" && SalePrice != "" && FileUpload != null)
            {
                string filename = FileUpload.FileName;
                string targetpath = Server.MapPath("~/images/ImageProducts/");
                if (!(System.IO.Directory.Exists(targetpath)))
                {
                    System.IO.Directory.CreateDirectory(targetpath);
                }
                FileUpload.SaveAs(targetpath + filename);
                string Image = "images/ImageProducts/" + filename;
                menu_temp.IDDish = "D" + querryDishesCount.Count() + "-" + String.Format("{0:ddMMyyyyHHmmss}", DateTime.Now);
                menu_temp.DishName = DishName;
                menu_temp.Ingredient = Ingredient;
                menu_temp.ImportPrice = Convert.ToDouble(ImportPrice);
                menu_temp.SalePrice = Convert.ToDouble(SalePrice);
                menu_temp.Image = Image;
                menu_temp.Category = Category;

                if (ModelState.IsValid)
                {
                    _db.Menus.Add(menu_temp);
                    _db.SaveChanges();
                    var success = new
                    {
                        title = "Thông báo",
                        message = "Tạo món ăn thành công",
                        type = true,
                    };
                    return Json(success, JsonRequestBehavior.AllowGet);
                }
            }
            else
            {
                string error = "";
                if (menu != null)
                {
                    error = "menu";

Views/Administrator_Setting/CreateDish.cshtml
@model Project_Web.Models.Menu
@{
    ViewBag.Title = "Tạo món ăn";
}
<head>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="~/fonts/material-icon/css/material-design-iconic-font.min.css">
    <link rel="stylesheet" href="~/Content/CreateDish.css">
</head>
<body>
    <div class="main">
        <section class="signup">
            <div class="container">
                <div class="signup-content">
                    <form method="POST" id="signup-dish-form" enctype="multipart/form-data" action="/Administrator_Setting/CreateDish" class="signup-form">
                        <h2 class="form-title">Tạo món ăn</h2>
                        <div class="form-group">
                            <input type="text" class="form-input" name="DishName" id="DishName" placeholder="Nhập tên món ăn" required />
                        </div>
                        <div class="form-group">
                            <input type="text" class="form-input" id="Ingredient" name="Ingredient" placeholder="Nhập thành phần món ăn" required />
                        </div>
                        <div class="form-group">
                            <input type="text" class="form-input" id="ImportPrice" name="ImportPrice" placeholder="Nhập giá nhập" required min="20000" />
                        </div>
                        <div class="form-group">
                            <input type="text" class="form-input" name="SalePrice" id="SalePrice" placeholder="Nhập giá bán" />
                        </div>
                        <div class="form-group" id="ImageG">
                            <label for="Image" class="form-input text-center"><i class="fa fa-upload">Chọn hình ảnh</i></label>
                            <input type="file" accept="image/*"  class="form-input" name="Image" id="Image" onchange="readURL(event);" style="display: none;" />
                        </div>
                        <div class="form-group file" id="file" style="display: none">
                            <div class="form-input-img-btn file">
                                <img id="showImage" class="image" />
                                <a class="remove-img" id="remove-img" onclick="reset($('#Image'))"><i class="fa fa-trash">Xóa</i></a>
                            </div>
                        </div>
                        <div class="form-group">
                            <select class="custom-select" id="SelectCategory" name="Category">
                                <option disabled selected>Phân loại</option>
                                <option value="Cá">Cháo cá</option>
                                <option value="Thịt">Cháo thịt</option>
                                <option value="Rau">Cháo chay</option>
                                <option value="Hải sản">Cháo hải sản</option>
                                <option value="Ăn liền">Cháo ăn liền</option>
                            </select>
                        </div>
                        <div class="form-group">
                            <input type="submit" name="submit" id="submit" class="form-submit" value="Lưu món ăn" />
                        </div>
                        <div id="res"></div>
                    </form>
                    <form enctype="multipart/form-data" id="formExcel">
                        <div class="form-group">
                            <input type="file" class="form-input" name="FileUpload" id="FileUpload" />
                        </div>
                        <div class="form-group">
                            <div class="excel">
                                <button type="submit" class="excelImport" id="submitExcel">Thêm vào database</button>
                                <a href="/Administrator_Setting/DownLoadTemplate_Menu" class="excelImport">Tải về</a>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </section>
    </div>
    <script src="~/Scripts/jquery-3.5.1.js"></script>
    <script src="~/Scripts/jquery-3.5.1.min.js"></script>
    <script src="~/Scripts/CreateDish.js"></script>
</body>

Views/Administrator_Setting/CreateSeller.cshtml
@using Project_Web.Models;
@{
    ViewBag.Title = "Tạo chủ cửa hàng";
    Database_PorridgeSellingManagementStoreEntities _db = new Database_PorridgeSellingManagementStoreEntities();
}
<head>
    <link rel="stylesheet" href="~/fonts/material-icon/css/material-design-iconic-font.min.css">
    <link rel="stylesheet" href="~/Content/CreateSeller.css">
</head>
<body>
    <div class="main">
        <section class="signup">
            <div class="container">
                <div class="signup-content">
                    <form method="POST" id="signup-seller-form" action="/Administrator_Setting/CreateSeller" class="signup-form">
                        <h2 class="form-title">Tạo chủ cửa hàng</h2>
                        <div class="form-group">
                            <input type="text" class="form-input" name="Username" id="Username" placeholder="Nhập tên tài khoản" required />
                        </div>
                        <div id="showError_Username"></div>
                        <div class="form-group">
                            <input type="password" class="form-input" name="Password" id="Password" placeholder="Nhập mật khẩu" required />
                            <span toggle="#Password" class="zmdi zmdi-eye field-icon toggle-password"></span>
                        </div>
                        <div id="showError_Password"></div>
                        <div class="form-group">
                            <input type="password" class="form-input" name="re_password" id="re_password" placeholder="Nhập lại mật khẩu" required />
                        </div>
                        <div id="showError"></div>
                        <div class="form-group">
                            <input type="text" class="form-input" name="Fullname" id="Fullname" placeholder="Nhập tên đầy đủ" required />
                        </div>
                        <div id="showError_Fullname"></div>
                        <div class="form-group">
                            <select class="custom-select" name="Province" id="ProvinceSelect">
                                <option disabled selected>Chọn Tỉnh/Thành phố</option>
                                @{
                                    var provinces = (from s in _db.Provinces
                                                     select s).ToList();
                                    foreach (var pro in provinces)
                                    {
                                        <option value="@pro.Name">@pro.Type @pro.Name</option>
                                    }
                                }
                            </select>
                        </div>
                        <div class="form-group District" id="District">
                            <select class="custom-select" name="District" id="DistrictSelect">
                                <option disabled selected>Chọn Quận/Huyện</option>
                            </select>
                        </div>
                        <div class="form-group Ward" id="Ward">
                            <select class="custom-select" name="Ward" id="WardSelect">
                                <option disabled selected>Chọn Phường/Xã</option>
                            </select>
                        </div>
                        <div class="form-group">
                            <input type="text" class="form-input" id="Address" name="Address" placeholder="Nhập địa chỉ của bạn" required />
                        </div>
                        <div id="showError_Address"></div>
                        <div class="form-group">
                            <input type="email" class="form-input" name="Email" id="Email" placeholder="Nhập E-mail của bạn" required />
                        </div>
                        <div id="showError_Email"></div>
                        <div class="form-group">
                            <input type="tel" class="form-input" id="PhoneNumber" name="PhoneNumber" placeholder="Nhập số điện thoại" required />
                        </div>
                        <div id="showError_PhoneNumber"></div>
                        <div class="form-group">
                            <div class="form-input">
                                <select class="custom-select" id="Role" name="Role">
                                    <option disabled="disabled" selected="selected">Chức vụ</option>
                                    <option value="Administrator">Administrator</option>
                                    <option value="Seller">Seller</option>
                                    <option value="Customer">Customer</option>
                                </select>
                            </div>
                        </div>
                        <div class="form-group">
                            <input type="submit" name="submit" id="submit" class="form-submit" value="Tạo tài khoản" />
                        </div>
                    </form>
                    <div class="textValidation">
                        @ViewBag.Message
                    </div>
                </div>
            </div>
        </section>
    </div>
</body>
<script src="~/Scripts/jquery-3.5.1.js"></script>
<script src="~/Scripts/CreateSeller.js"></script>

Views/Administrator_Setting/CreateStore.cshtml
@{
    ViewBag.Title = "Tạo cửa hàng";
}
@model Project_Web.Models.Store
<head>
    <link rel="stylesheet" href="~/fonts/material-icon/css/material-design-iconic-font.min.css">
    <link rel="stylesheet" href="~/Content/CreateStore.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>
</head>
<body>
    <div class="main">
        <section class="signup">
            <div class="container">
                <div class="signup-content">
                    <div class="tab">
                        <button class="tablinks" onclick="openForm(event, 'Store')">Cửa hàng</button>
                        <button class="tablinks" onclick="openForm(event, 'Staff')">Nhân viên</button>
                        <button class="tablinks" onclick="openForm(event, 'Dish')">Món ăn</button>
                    </div>
                    <div class="tabcontent" id="Store">
                        @{Html.RenderAction("_TabStore", "Administrator_Setting", new { page = 1 });}
                    </div>
                    <div class="tabcontent" id="Staff">
                        @*@Html.Partial("~/Views/Administrator_Setting/_TabStaff.cshtml")*@
                        @{Html.RenderAction("_TabStaff", "Administrator_Setting", new { page = 1 });}
                    </div>
                    <div class="tabcontent" id="Dish">
                        @*@Html.Partial("~/Views/Administrator_Setting/_TabDish.cshtml")*@
                        @{Html.RenderAction("_TabDish", "Administrator_Setting", new { page = 1 });}
                    </div>
                </div>
            </div>
        </section>
    </div>
</body>
<script src="~/Scripts/jquery-3.5.1.min.js"></script>
<script src="~/Scripts/jquery-3.5.1.js"></script>
<script src="~/Scripts/jquery.validate.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/CreateStore.js"></script>

Views/Administrator_Setting/_TabDish.cshtml
@using Project_Web.Models;
@using PagedList.Mvc;

@model PagedList.IPagedList<Project_Web.Models.Menu_Stores>
@{
    Database_PorridgeSellingManagementStoreEntities _db = new Database_PorridgeSellingManagementStoreEntities();
}
<div class="button-popup">
    <button id="open-popup-dish-form" class="form-submit" onclick="openPopupDishForm()">Thêm món ăn</button>
    <table class="table table-bordered">
        <thead>
            <tr>
                <th style="width: 30% ">Tên cửa hàng</th>
                <th style="width: 25% ">Vị trí</th>
                <th style="width: 20% ">Tên món ăn</th>
                <th style="width: 25% ">Số lượng</th>
            </tr>
        </thead>
        <tbody id="ListData">
            @{

                foreach (var s in Model)
                {
                    var store = _db.Stores.SingleOrDefault(n => n.IDStore == s.IDStore);
                    var dish = _db.Menus.SingleOrDefault(n => n.IDDish == s.IDDish);
                    if (s.Available == null)
                    {
                        s.Available = 0;
                    }
                    <tr>
                        <td>@store.StoreName</td>
                        <td>@store.Location</td>
                        <td>@dish.DishName</td>
                        <td>@s.Available</td>
                    </tr>

                }
            }
        </tbody>
    </table>
    <div class="paging">
        <div class="paging-show">
            Trang: @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) / @Model.PageCount
        </div>
        <div class="paging-choose" id="myPagerDish">
            @Html.PagedListPager(Model, page => Url.Action("_TabDish", new { page }),
           PagedListRenderOptions.EnableUnobtrusiveAjaxReplacing(PagedListRenderOptions.ClassicPlusFirstAndLast
           , new AjaxOptions
           { InsertionMode = InsertionMode.Replace, HttpMethod = "Get", UpdateTargetId = "Dish" }))
        </div>
    </div>

</div>
<div class="signup-content-dish" id="signup-content-dish">
    <div class="signup-background-dish" id="signup-background-dish">
        <span class="remove-icon" id="close-popup-form" onclick="closePopupForm()">x</span>
        <form method="POST" action="/Administrator_Setting/AddDish" id="signup-form-dish" class="signup-form-dish">
            <h2 class="form-title h2-dish">Tạo món ăn cho cửa hàng</h2>
            <div class="form-group">
                <select class="custom-select" id="LocationSelectDish" name="Location">
                    <option disabled selected>Location</option>
                    <option value="Quận 1">Quận 1</option>
                    <option value="Quận 2">Quận 2</option>
                    <option value="Quận 3">Quận 3</option>
                    <option value="Quận 4">Quận 4</option>
                    <option value="Quận 5">Quận 5</option>
                    <option value="Quận 6">Quận 6</option>
                    <option value="Quận 7">Quận 7</option>
                    <option value="Quận 8">Quận 8</option>
                    <option value="Quận 9">Quận 9</option>
                    <option value="Quận 10">Quận 10</option>
                    <option value="Quận 11">Quận 11</option>
                    <option value="Quận 12">Quận 12</option>
                    <option value="Quận Thủ Đức">Quận Thủ Đức</option>
                    <option value="Quận Gò Vấp">Quận Gò Vấp</option>
                    <option value="Quận Bình Thạnh">Quận Bình Thạnh</option>
                    <option value="Quận Tân Bình">Quận Tân Bình</option>
                    <option value="Quận Tân Phú">Quận Tân Phú</option>
                    <option value="Quận Phú Nhuận">Quận Phú Nhuận</option>
                    <option value="Huyện Củ Chi">Huyện Củ Chi</option>
                    <option value="Huyện Hóc Môn">Huyện Hóc Môn</option>
                    <option value="Huyện Bình Chánh">Huyện Bình Chánh</option>
                    <option value="Huyện Nhà Bè">Huyện Nhà Bè</option>
                    <option value="Huyện Cần Giờ">Huyện Cần Giờ</option>
                </select>
            </div>
            <div class="form-group" id="StoreNameList">
                <select class="custom-select" name="StoreName" id="StoreNameSelect">
                </select>
            </div>
            <div class="form-group show-dish-list" id="DishNameList">
                <h6 class="form-title">Chọn món ăn</h6>
                <div class="list-dish" id="listdish" style="overflow-y: scroll; height: 200px;">
                </div>
            </div>
        </form>
    </div>
</div>